### ISSUE TITLE
Broken image links

### ISSUE THREAD

**Issue by iamdto** [symfony/symfony-marketing#119]
Looks like on the [mailing list](http://symfony.com/mailing-lists) page image links are broken.

**Comment by javiereguiluz** [comment]
Closing it because the design of that page has changed and the error is no longer present. Thanks!

**Comment by iamdto** [comment]
:+1:

Not sure if it's just me but I can't see nothing on this page. Just the title and a grey empty box.

**Comment by xabbuh** [comment]
@iamdto same here

@javiereguiluz Is the page currently being under reconstruction?

**Comment by OskarStark** [comment]
me too

![bildschirmfoto 2015-08-20 um 10 37 27](https://cloud.githubusercontent.com/assets/995707/9379141/83247fb0-4727-11e5-8c76-871339458251.png)

**Comment by javiereguiluz** [comment]
Yes. The problem was that the template expects the new translation contents but they weren't available. Two days ago we finally merged the new contents: https://github.com/symfony/symfony-marketing/pull/280

It seems that the symfony.com server hasn't correctly loaded the new contents of this repository. I'm going to ask around. Thanks!
