### ISSUE TITLE
Inconsistent "Get Started" section

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-marketing#254]
The [Get Started](http://symfony.com/get_started) section on the Symfony web site looks a bit weird for two reasons:

* The [Symfony Distributions](http://symfony.com/distributions) and [symfony1 Legacy](http://symfony.com/legacy) items use the old layout:

  ![distributions](https://cloud.githubusercontent.com/assets/1957048/7665403/343878ec-fbb5-11e4-9371-9554092ff471.png)
* The *Get Started* item in the horizontal navigation is not highlighted when accessing the [Download Symfony](http://symfony.com/download) or the [Symfony Components](http://symfony.com/components) section.

**Comment by fabpot** [comment]
ping @javiereguiluz

**Comment by xabbuh** [comment]
http://symfony.com/get-started seems to no longer exist.

ping @javiereguiluz

**Comment by javiereguiluz** [comment]
@xabbuh thanks for this multiple bug report. Let's get into details:

  * `/get-started` URL no longer exists ... because it never existed ;) It was `/get_started`
  * `Get Started` section has been removed and merged into `What is Symfony`
  * The Symfony Distributions no longer uses the old design (but the "Legacy symfony 1 page" still does - this is on purpose to differentiate more from Symfony 2 and 3)
  * Download and Components sub-sections now highlight the "What is Symfony" menu item

I'm closing this issue because I consider everything fixed. If you don't agree, please reopen it. Thanks!

**Comment by xabbuh** [comment]
@javiereguiluz How do we now access the distribution page? I don't see any links to this page? Or does the page only exist for BC?

**Comment by javiereguiluz** [comment]
The distribution page is linked from the Download page: http://symfony.com/download (at the bottom)

**Comment by xabbuh** [comment]
ah thanks
