### ISSUE TITLE
How to add new translation

### ISSUE THREAD

**Issue by ardianys** [symfony/symfony-marketing#298]
My Indonesian translation request already accepted,
Then, how do I add new content for ID ?

**Comment by javiereguiluz** [comment]
@ardianys I took us a long time, but we finally merged your work :)

To add new translations, you just need to fork this repository, create a new branch, translate one page and submit the changes to create the corresponding pull request. We prefer if you translate just 1 page per pull request because the review process is very quick and your work will be easier. *Terima kasih*

**Comment by ardianys** [comment]
I already forked it before,
I think I just have to create new file inside ID directory, isn't it ?

**Comment by javiereguiluz** [comment]
@ardianys yes. Just create the new file, translate it and commit the changes to GitHub to create a pull request.

I'm closing this issue as "solved", but if you have any problem or doubt during the process of making the pull request, please create a new issue or describe your problem in the pull request description and we'll help you. Thanks!
