### ISSUE TITLE
irc sidebar link broken

### ISSUE THREAD

**Issue by ofbeaton** [symfony/symfony-marketing#74]
I tried to find where I could submit a pull request for the sidebar, but alas I did not find it.

The sidebar link for "IRC Channel" url points to irc-channel instead of irc

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue and I'm really sorry for providing such a late feedback. The good news is that this error is no longer present because of the changes in the website design. By the way, we'll soon provide a new global `/support` page which will make it unnecessary to link to the specific IRC page. Thanks.
