### ISSUE TITLE
Add a part to sell Symfony compare to other language like Ruby, Python

### ISSUE THREAD

**Issue by nicolas-bastien** [symfony/symfony-marketing#99]
This website is a great source of arguments to choose Symfony2 as a PHP framework.

I think it could be great to add a part to compare it with Ruby and Python frameworks.

As a web developers, it's some times hard to sell PHP.
This would help a lot.

**Comment by javiereguiluz** [comment]
Thanks for your proposal and I'm sorry for not having provided any feedback so far.

I'm closing this issue because soon we're gonna revamp the Quick Tour to transform it into a real showcase of the best features provided by Symfony. The intention is not only to show how great Symfony is compared with other PHP frameworks but with any other framework developed with different languages.

By the way, since this issue was reported, PHP has improved a lot and the upcoming PHP7 release hopefully will make it easier to sell PHP to clients.

**Comment by nicolas-bastien** [comment]
ok @javiereguiluz thanks for the feedback
